### ISSUE TITLE
libblas.a

### ISSUE THREAD

**Issue by matthewchung74** [cmusphinx/pocketsphinx-ios-demo#4] opened 2015-04-21 01:57 UTC
Hello nshmyrev,

I have an issue linking to libblas.a when compiling pocketsphinx-5prealpha and was wondering if you had this same issue? If so, how you got around it? Here is the error message

```
ld: library not found for -lblas
```

also, you are supposed to run the script on both sphinxbase-5prealpha and pocketsphinx-5prealpha right?

**Comment by nshmyrev** [comment] 2015-04-21 06:57
Duplicate of #2

**Closed as completed by nshmyrev** 2015-04-21 06:57 UTC
